const LOGIN_SCREEN = 'LOGIN_SCREEN';
const REGISTER_SCREEN = 'REGISTER_SCREEN';
const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
const ADD_TASKS_SCREEN = 'ADD_TASKS_SCREEN';

export {LOGIN_SCREEN, REGISTER_SCREEN, DASHBOARD_SCREEN, ADD_TASKS_SCREEN};
